{{- if .Values.api.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 annotations:
   kubernetes.io/ingress.class: nginx
 name: {{ .Values.api.name }}
spec:
 rules:
 - host: {{ .Values.api.ingress.host }}
   http:
     paths:
     - backend:
         service:
           name: {{ .Values.api.name }}
           port:
             number: {{ .Values.api.ingress.port }}
       path: /
       pathType: Prefix
{{- end }}
