{{- if .Values.db.enabled }}
apiVersion: {{ .Values.db.api_version }}
kind: PersistentVolumeClaim
metadata:
  name: pg-db
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.db.pvc.size }}
  storageClassName: {{ .Values.db.pvc.storageClass }}
{{- end }}
